In [30]:
from datasets import load_dataset
mrpc = load_dataset('glue', 'mrpc',split='test')


Reusing dataset glue (/root/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)


In [31]:
from datasets import ClassLabel
for key in mrpc.features:
    if isinstance(mrpc.features[key],ClassLabel):
        print(mrpc.features[key].names)
# mrpc[0]['label'].names

['not_equivalent', 'equivalent']


In [39]:
import torch
test = torch.load('/mlx_devbox/users/linzhisheng.2021/ATTEMPT/attempt/result/stage1/mnli_fp32/task_embedding.pt', map_location=torch.device('cpu'))
input = torch.rand(44,768)

x = torch.rand(128,44,768)
print(x.shape[1] > 32)
# print(x[:,0,:].unsqueeze(1))
# print(x[:,:1,:])


# task_list = torch.nn.ParameterList()
# task_list.append(test['task_shared'])
# task_list.append(test['task_shared'])
# task_list

# attention_embedding = torch.zeros_like(input)
# for embedding in task_list:
#     # print(embedding)
#     dot = torch.matmul(input, embedding.transpose(0,1))
#     prob = torch.nn.functional.softmax(dot,dim=-1)
#     o = torch.matmul(prob, embedding)
#     attention_embedding = attention_embedding + o


# test['decoder.block.11.layer.2.DenseReluDense.wo.lora_B']

True


In [3]:
import torch.nn as nn
import torch
import numpy as np
# t1= nn.Parameter(torch.zeros((64, 768)))
# t2= nn.Parameter(torch.zeros((64, 768)))
x = torch.randn(3,127)
t1 = torch.randn(127,4)
t2 = torch.randn(127,4)
# a = torch.nn.functional.cosine_similarity(t1.flatten(),t2.flatten(),dim=0)
print(x@t1)

print(nn.LayerNorm(4)(x@t1))
# print(x@t2)


t = np.random.permutation(range(5000))
t[4999]

tensor([[  0.6041,  -7.1097,   6.5655,  -3.0846],
        [ -4.7148,   5.2828,   4.3676,  -2.3006],
        [-10.4563,   1.5535,   7.8542,   7.6495]])
tensor([[ 0.2704, -1.2629,  1.4553, -0.4628],
        [-1.2598,  1.0841,  0.8696, -0.6938],
        [-1.6285, -0.0130,  0.8345,  0.8070]],
       grad_fn=<NativeLayerNormBackward0>)


1701

In [5]:
import sklearn
import sklearn.metrics
t1 = ['asd']
t2 = ['asd']
sklearn.metrics.f1_score(t1,t2)

/root/miniconda3/envs/attempt_env/lib/python3.8/site-packages/numpy/lib/arraysetops.py:608: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
/root/miniconda3/envs/attempt_env/lib/python3.8/site-packages/scikit_learn-0.24.2-py3.8-linux-x86_64.egg/sklearn/metrics/_classification.py:1495: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(


0.0

In [8]:
import torch
from torch.nn.functional import softmax

x = torch.randn(4,12,768)
gate_x = x[:,0,:]
w = torch.nn.Parameter(torch.randn(768, 6))

test = x@w

test[:,:,0] = test[:,:,0] + 999999999
test[:,:,1:] = 0
print(test.shape)
print(test)


w_noise = torch.nn.Parameter(torch.randn(768, 6))
softplus = torch.nn.Softplus()
softmax = torch.nn.Softmax(1)

noise_epsilon = 1e-2




clean_logits = gate_x@w



raw_noise_stddev = gate_x @ w_noise
noise_stddev = ((softplus(raw_noise_stddev) + noise_epsilon))
noisy_logits = clean_logits + (torch.randn_like(clean_logits) * noise_stddev)



logits = noisy_logits

logits




# logits = logits.sum(0)
# print(logits)
# logits = torch.nn.functional.softmax(logits)
# print(logits)

# print(torch.argmax(logits))
# k=4
# num_experts=6
# top_logits, top_indices = logits.topk(min(k + 1, num_experts), dim=1)
# top_k_logits = top_logits[:, :k]
# top_k_indices = top_indices[:, :k]

# top_k_gates = softmax(top_k_logits)
# # print(top_k_indices)



# zeros = torch.zeros_like(logits, requires_grad=True)
# gates = zeros.scatter(1, top_k_indices, top_k_gates)
# load = (gates>0).sum(0)
# # print(gates)
# # load
# # (output>0).sum(0)



# dispatcher = SparseDispatcher(num_experts, gates)

# expert_inputs = dispatcher.dispatch(x)

torch.Size([4, 12, 6])
tensor([[[1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0

tensor([[-38.0970, -10.4717, -60.2004, -17.5134,  26.7224, -25.1057],
        [ 17.2692,  29.1443, -34.3721,   9.5295,  -6.5533,  15.3158],
        [ 10.8645, -16.4372,  13.4175, -14.6265, -26.2576,  -8.9261],
        [-26.7573,   4.3462, -19.2858,  29.9002, -34.1080, -23.1021]],
       grad_fn=<AddBackward0>)

In [7]:
import torch
x = torch.randn(16,5,768)
x = x.sum(dim=1)
# x = x[:,0,:]
x = x.unsqueeze(1)
print(x.shape)
# res = []
# res.append(torch.randn(5,5,768))
# res.append(torch.randn(5,5,768))
# xx = torch.randn(5,1,2)

# max_index = torch.argmax(xx,dim=2)
# print(xx)
# print(max_index)

# result = torch.zeros_like(xx)
# result.scatter_(2, max_index.unsqueeze(2), 1)
# print(result)

# xx[:,:,0] = 999999999
# xx[:,:,1:] = 0

# t = torch.nn.Softmax(dim=-1)
# # x.shape
# print(xx)

# gg = t(xx).unsqueeze(3)


# print(gg.shape)
# output = torch.stack(res,dim=3) @ gg
# output = output.squeeze()
# print(res[0][0,0,0])
# print(res[1][0,0,0])
# print(output[0,0,0])
# print(output)
# print(gg.shape)
# print(torch.stack(res,dim=3).shape)

torch.Size([16, 1, 768])


In [8]:
from transformers import (
    AutoTokenizer,
)

tokenizer = AutoTokenizer.from_pretrained('t5-base')
tokenizer.add_special_tokens({'sep_token':'<eot>'})

1

In [29]:
model_inputs = tokenizer("Given a question and a context sentence, the task is to determine whether the context sentence contains the answer to the question.")

print(model_inputs)
print(len(model_inputs['input_ids']))

# model_inputs = tokenizer("sentence:I love you!", max_length=128,
#                                  padding=True, truncation=True)
# model_inputs
# tokenizer.sep_token_id


{'input_ids': [9246, 3, 9, 822, 11, 3, 9, 2625, 7142, 6, 8, 2491, 19, 12, 2082, 823, 8, 2625, 7142, 2579, 8, 1525, 12, 8, 822, 5, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
27


In [23]:
import numpy as np
import torch.nn as nn
import torch
prefix_dim = len(model_inputs['input_ids'])


shared = nn.Embedding(30000, 768)
prefix_shared = nn.Parameter(torch.zeros((prefix_dim, 768)))
# indices = np.random.permutation(range(5000))[:prefix_dim]
indices = model_inputs['input_ids']
shared.weight.shape

print(indices, prefix_dim)


init_weight = shared.state_dict()[
                "weight"][indices]
# print(init_weight.shape)
prefix_shared.data = init_weight.clone().detach()

prefix_shared.data


inputs_embeds = torch.rand(16, 10, 768)
print(inputs_embeds.shape)
inputs_embeds = torch.cat([prefix_shared.unsqueeze(0).repeat(
                    inputs_embeds.shape[0], 1, 1), inputs_embeds], dim=1)
inputs_embeds.shape

[9246, 3, 9, 822, 11, 3, 9, 2625, 7142, 6, 8, 2491, 19, 12, 2082, 823, 8, 2625, 7142, 2579, 8, 1525, 12, 8, 822, 5, 7142, 10, 196, 333, 25, 55, 1] 33
torch.Size([16, 10, 768])


torch.Size([16, 43, 768])

In [75]:
import torch

q = torch.randn(12,768)
k = torch.randn(2,768).transpose(0,1)
v = torch.randn(2,768)
score = torch.matmul(q,k)
print(score.shape)

o = torch.matmul(score, v)
print(o.shape)

torch.Size([12, 2])
torch.Size([12, 768])


In [73]:
task_embedding = nn.Parameter(torch.Tensor(torch.randn(768)))
task_embedding.data

tensor([ 0.5179,  1.1512, -1.2449,  1.1654, -0.0081, -1.5165,  0.6880, -0.7525,
         0.0338,  1.3546, -0.0811,  0.5938,  0.7014, -1.1654,  0.9075, -0.5658,
         0.5883,  0.4706, -0.2626, -0.5282, -0.1247,  0.2789,  1.1579,  0.4144,
         0.8306,  0.1764, -0.2924, -0.1448,  0.9455, -1.1846, -1.9123, -1.3248,
        -1.2095, -0.8503,  0.1216, -2.9493,  0.7450, -0.3030, -0.0480, -0.7447,
         0.4423,  0.1080,  0.9750,  0.4162, -1.4857, -1.0951, -0.1703,  0.9099,
         1.2162,  0.8580,  0.3220, -0.3006,  0.0605,  0.0405, -0.5971, -1.1596,
        -0.1575, -0.0504,  0.1713, -3.4517, -0.0266,  1.0404, -0.4456,  1.0558,
         0.5723,  0.5811, -0.2051, -2.7935, -1.0041,  0.5495,  1.3382,  0.8375,
        -2.0622, -0.8512,  0.4207,  1.2977,  2.0883,  0.1503, -2.1810,  0.4034,
         0.8343,  0.6502, -0.1412,  0.5254, -0.0167,  0.5114,  0.1894,  0.4083,
        -0.0739,  0.8947, -0.7718, -0.6257,  0.3006, -0.2854,  1.1327,  0.4030,
         0.9116,  1.1039,  1.3650, -0.53