In [30]:
from datasets import load_dataset
mrpc = load_dataset('glue', 'mrpc',split='test')


Reusing dataset glue (/root/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)


In [31]:
from datasets import ClassLabel
for key in mrpc.features:
    if isinstance(mrpc.features[key],ClassLabel):
        print(mrpc.features[key].names)
# mrpc[0]['label'].names

['not_equivalent', 'equivalent']


In [ ]:
import torch
test = torch.load('/mlx_devbox/users/linzhisheng.2021/ATTEMPT/attempt/outputs/lora_qnli/lora.pt', map_location=torch.device('cpu'))

test.keys()
test['decoder.block.11.layer.2.DenseReluDense.wo.lora_B']

In [3]:
import torch.nn as nn
import torch
import numpy as np
# t1= nn.Parameter(torch.zeros((64, 768)))
# t2= nn.Parameter(torch.zeros((64, 768)))
x = torch.randn(3,127)
t1 = torch.randn(127,4)
t2 = torch.randn(127,4)
# a = torch.nn.functional.cosine_similarity(t1.flatten(),t2.flatten(),dim=0)
print(x@t1)

print(nn.LayerNorm(4)(x@t1))
# print(x@t2)


t = np.random.permutation(range(5000))
t[4999]

tensor([[  0.6041,  -7.1097,   6.5655,  -3.0846],
        [ -4.7148,   5.2828,   4.3676,  -2.3006],
        [-10.4563,   1.5535,   7.8542,   7.6495]])
tensor([[ 0.2704, -1.2629,  1.4553, -0.4628],
        [-1.2598,  1.0841,  0.8696, -0.6938],
        [-1.6285, -0.0130,  0.8345,  0.8070]],
       grad_fn=<NativeLayerNormBackward0>)


1701

In [5]:
import sklearn
import sklearn.metrics
t1 = ['asd']
t2 = ['asd']
sklearn.metrics.f1_score(t1,t2)

/root/miniconda3/envs/attempt_env/lib/python3.8/site-packages/numpy/lib/arraysetops.py:608: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
/root/miniconda3/envs/attempt_env/lib/python3.8/site-packages/scikit_learn-0.24.2-py3.8-linux-x86_64.egg/sklearn/metrics/_classification.py:1495: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(


0.0

In [8]:
import torch
from torch.nn.functional import softmax

x = torch.randn(4,12,768)
gate_x = x[:,0,:]
w = torch.nn.Parameter(torch.randn(768, 6))

test = x@w

test[:,:,0] = test[:,:,0] + 999999999
test[:,:,1:] = 0
print(test.shape)
print(test)


w_noise = torch.nn.Parameter(torch.randn(768, 6))
softplus = torch.nn.Softplus()
softmax = torch.nn.Softmax(1)

noise_epsilon = 1e-2




clean_logits = gate_x@w



raw_noise_stddev = gate_x @ w_noise
noise_stddev = ((softplus(raw_noise_stddev) + noise_epsilon))
noisy_logits = clean_logits + (torch.randn_like(clean_logits) * noise_stddev)



logits = noisy_logits

logits




# logits = logits.sum(0)
# print(logits)
# logits = torch.nn.functional.softmax(logits)
# print(logits)

# print(torch.argmax(logits))
# k=4
# num_experts=6
# top_logits, top_indices = logits.topk(min(k + 1, num_experts), dim=1)
# top_k_logits = top_logits[:, :k]
# top_k_indices = top_indices[:, :k]

# top_k_gates = softmax(top_k_logits)
# # print(top_k_indices)



# zeros = torch.zeros_like(logits, requires_grad=True)
# gates = zeros.scatter(1, top_k_indices, top_k_gates)
# load = (gates>0).sum(0)
# # print(gates)
# # load
# # (output>0).sum(0)



# dispatcher = SparseDispatcher(num_experts, gates)

# expert_inputs = dispatcher.dispatch(x)

torch.Size([4, 12, 6])
tensor([[[1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [1.0000e+09, 0.0000e+00, 0.0000e+00, 0

tensor([[-38.0970, -10.4717, -60.2004, -17.5134,  26.7224, -25.1057],
        [ 17.2692,  29.1443, -34.3721,   9.5295,  -6.5533,  15.3158],
        [ 10.8645, -16.4372,  13.4175, -14.6265, -26.2576,  -8.9261],
        [-26.7573,   4.3462, -19.2858,  29.9002, -34.1080, -23.1021]],
       grad_fn=<AddBackward0>)

In [7]:
import torch
x = torch.randn(16,5,768)
x = x.sum(dim=1)
# x = x[:,0,:]
x = x.unsqueeze(1)
print(x.shape)
# res = []
# res.append(torch.randn(5,5,768))
# res.append(torch.randn(5,5,768))
# xx = torch.randn(5,1,2)

# max_index = torch.argmax(xx,dim=2)
# print(xx)
# print(max_index)

# result = torch.zeros_like(xx)
# result.scatter_(2, max_index.unsqueeze(2), 1)
# print(result)

# xx[:,:,0] = 999999999
# xx[:,:,1:] = 0

# t = torch.nn.Softmax(dim=-1)
# # x.shape
# print(xx)

# gg = t(xx).unsqueeze(3)


# print(gg.shape)
# output = torch.stack(res,dim=3) @ gg
# output = output.squeeze()
# print(res[0][0,0,0])
# print(res[1][0,0,0])
# print(output[0,0,0])
# print(output)
# print(gg.shape)
# print(torch.stack(res,dim=3).shape)

torch.Size([16, 1, 768])
